language: java

dist: trusty

addons:
  hosts:
  - jbake-gradle-builder
  hostname: jbake-gradle-builder

notifications:
  irc:
    - "chat.freenode.net#jbake"

install: true

cache:
    directories:
        - $HOME/.m2
        - $HOME/.gradle

before_script:
    - ./gradlew --version

script:
    - TERM=dumb ./gradlew build jacocoTestReport

matrix:
  include:
    - jdk: oraclejdk9
    - jdk: oraclejdk8
    - jdk: openjdk8
    - jdk: openjdk7
      dist: precise

after_success:
    - ./gradlew coveralls
